GET https://phonebook-backend-billowing-wave-3003.fly.dev/api/persons/

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json
{
    "name": "hello",
    "number": "927-1248128"
}

###
POST https://phonebook-backend-billowing-wave-3003.fly.dev/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "hello",
    "number": "927-1248128"
}